spring:
  application:
    name: ChainMakersService
  profiles:
    active: dev

server:
  port: 80
  servlet:
    context-path: /cm

integration:
  trace_requests: false

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2data/dev
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false

    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/chainMakers.changelog_master.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
    port: 80

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spark.master: local
spark.jars:

---
spring:
  profiles: cloud
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2data/dev
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      org:
        hibernate:
          envers:
            do_not_audit_optimistic_locking_field: false

    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    change-log: classpath:db/chainMakers.changelog_master.xml
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8090

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spark.master: local
spark.jars:

logging:
  level:
    .: debug
    sparta.supplynetwork: debug
    org.springframework: warn
    org.apache: warn
    org.spark_project: warn
    com.zaxxer: warn
    org.hibernate: warn
    liquibase: warn
    springfox: warn
  pattern:
    console: "%msg%n"
